const express = require('express');
const http = require('http');
const https = require('https');
const fs = require('fs');
const socketIo = require('socket.io');
const mongoose = require('mongoose');
const path = require('path');
const bodyParser = require('body-parser');
const session = require('express-session');
const MongoStore = require('connect-mongo');
const bcrypt = require('bcryptjs');
const multer = require('multer');
const asyncLib = require('async');
const sharp = require('sharp');
require('dotenv').config();
const app = express();
const ChecklistAssignment = require('./models/ChecklistAssignment');
const router = express.Router();
const qrcode = require('qrcode');

// --- SERVER CREATION LOGIC (UPDATED FOR MKCERT) ---
let server;
if (process.env.NODE_ENV === 'production') {
  console.log('Running in production mode (HTTP server).');
  server = http.createServer(app);
} else {
  console.log('Running in development mode (HTTPS server with mkcert).');
  try {
    // IMPORTANT: Replace these filenames with the exact names of the files
    // generated by mkcert in the previous step.
    const options = {
      key: fs.readFileSync('localhost+3-key.pem'), // <-- UPDATE THIS FILENAME
      cert: fs.readFileSync('localhost+3.pem')     // <-- UPDATE THIS FILENAME
    };
    server = https.createServer(options, app);
  } catch (error) {
    console.error('Could not find SSL certificates for mkcert. Please run "mkcert" to generate them.');
    console.error(error);
    server = http.createServer(app);
  }
}
const io = socketIo(server);
// --- END OF SERVER CREATION LOGIC ---

// Set up view engine and static files
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));

// --- THE FIX: TRUST THE REVERSE PROXY ---
// This tells Express to trust the 'X-Forwarded-*' headers set by Nginx
if (process.env.NODE_ENV === 'production') {
  app.set('trust proxy', 1);
}
// --- END OF THE FIX ---

app.use(express.static(path.join(__dirname, 'public')));

//Parsing JSON Requests
app.use(express.json());
// Middleware to parse URL-encoded bodies (for forms)
app.use(express.urlencoded({
    extended: true
}));


// Configure body parser
app.use(bodyParser.urlencoded({
    extended: true
}));

// --- UPDATED PRODUCTION-READY SESSION CONFIGURATION ---
app.use(session({
    secret: process.env.SESSION_SECRET || 'a_very_strong_secret_for_production',
    resave: false,
    saveUninitialized: false, // Recommended for production to prevent empty session records
    store: MongoStore.create({
        mongoUrl: process.env.MONGODB_URI,
        collectionName: 'sessions', // You can name the collection where sessions are stored
        ttl: 14 * 24 * 60 * 60 // Session time to live in seconds (e.g., 14 days)
    }),
    cookie: {
        maxAge: 14 * 24 * 60 * 60 * 1000, // Matches the ttl in milliseconds
        secure: process.env.NODE_ENV === 'production' // Use secure cookies in production (requires HTTPS)
    }
}));
// --- END OF UPDATED SESSION CONFIGURATION ---


// Flash message middleware to make messages available in views
app.use((req, res, next) => {
    res.locals.message = req.session.message;
    delete req.session.message;
    next();
});


// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI)
    .then(() => console.log('MongoDB connected'))
    .catch(err => console.error('MongoDB connection error:', err));


// Import models
const Asset = require('./models/Asset');
const Checklist = require('./models/Checklist');
const User = require('./models/User');
const Division = require('./models/Division');
const AssetCategory = require('./models/AssetCategory');
const Floor = require('./models/Floor');
const Zone = require('./models/Zone');
const Activity = require('./models/Activity');


// FUNGSI BARU UNTUN LOG AKTIVITAS
async function logActivity(userId, action, divisionId = null) {
    try {
        const user = await User.findById(userId).populate('division');
        if (!user) return;

        let divisionInfo = {};
        if (user.role === 'manager' || user.role === 'superuser') {
            if (divisionId) {
                const division = await Division.findById(divisionId);
                if (division) {
                    divisionInfo = { id: division._id, name: division.name };
                }
            }
        } else if (user.division) {
            divisionInfo = { id: user.division._id, name: user.division.name };
        }

        const newActivity = new Activity({
            user: { id: user._id, name: user.name },
            action,
            division: divisionInfo,
            role: user.role,
        });
        await newActivity.save();
    } catch (error) {
        console.error('Failed to log activity:', error);
    }
}


// Configure Multer to store uploaded files in a folder
const storage = multer.diskStorage({
    destination: function(req, file, cb) {
        cb(null, path.join(__dirname, 'public/uploads'));
    },
    filename: function(req, file, cb) {
        cb(null, Date.now() + '-' + file.originalname);
    }
});
const upload = multer({
    storage: storage
});

// Middleware for authentication
function ensureAuthenticated(req, res, next) {
    if (req.session && req.session.userId) {
        return next();
    }
    res.redirect('/login'); // Redirect unauthenticated users to login
}

// General role-based middleware to reduce redundancy
function ensureRole(role) {
    return (req, res, next) => {
        if (req.session && req.session.userRole === role) {
            return next();
        }
        console.warn(`Unauthorized access attempt by user ${req.session.userId} (Role: ${req.session.userRole})`);
        res.status(403).send(`Access denied: Only ${role}s allowed`);
    };
}

// Specific role-based middlewares using the generic function
const ensureSuperuser = ensureRole('superuser');
const ensureManager = ensureRole('manager');
const ensureSpv = ensureRole('spv');
const ensureTechnician = ensureRole('technician');




// Middleware to ensure the asset being accessed belongs to the user's division
async function ensureAssetBelongsToUser(req, res, next) {
    try {
        const asset = await Asset.findById(req.params.id);
        if (!asset) {
            return res.status(404).send('Asset not found');
        }
        if (asset.division.toString() !== req.session.userDivision) {
            return res.status(403).send('Access denied: This asset is not in your division');
        }
        req.asset = asset;
        next();
    } catch (error) {
        res.status(500).send(error.message);
    }
}

// Middleware baru untuk memastikan checklist milik divisi user
async function ensureChecklistBelongsToDivision(req, res, next) {
    try {
        const checklist = await Checklist.findById(req.params.id);
        if (!checklist) {
            return res.status(404).send('Checklist not found');
        }
        // Periksa apakah checklist.division sama dengan req.session.userDivision
        if (checklist.division.toString() !== req.session.userDivision) {
            return res.status(403).send('Access denied: You are not authorized to modify this checklist');
        }
        req.checklist = checklist;
        next();
    } catch (error) {
        res.status(500).send(error.message);
    }
}

// Image Compression Queue
const imageProcessingQueue = asyncLib.queue((task, callback) => {
    sharp(task.filePath)
        .rotate()
        .withMetadata()
        .resize({
            width: 600,
            withoutEnlargement: true
        })
        .jpeg({
            quality: 80,
            progressive: true,
            mozjpeg: true
        })
        .toFile(`processed/${path.basename(task.filePath)}`)
        .then(() => {
            fs.unlink(task.filePath, (unlinkErr) => {
                if (unlinkErr) {
                    console.error('Error deleting original file:', unlinkErr);
                }
                callback(null);
            });
        })
        .catch((error) => {
            console.error('Image processing error:', error);
            callback(error);
        });
}, 2);

const processedDir = path.join(__dirname, 'processed');
if (!fs.existsSync(processedDir)) {
    fs.mkdirSync(processedDir, {
        recursive: true
    });
}


// Serve the processed images folder as static
app.use('/processed', express.static(path.join(__dirname, 'processed')));

// Socket.io connection event
io.on('connection', (socket) => {
    console.log('A user connected');

    socket.on('new-alert', (data) => {
        io.emit('alert', data);
    });

    socket.on('disconnect', () => {
        console.log('User disconnected');
    });
});

// Helper function to escape regex special characters
function escapeRegex(string) {
    return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
}

// ------------------------------
// ROUTES
// ------------------------------

// Home page redirect to dashboard based on role
app.get('/', (req, res) => {
    if (req.session && req.session.userId) {
        const dashboardRoutes = {
            superuser: '/superuser/dashboard',
            manager: '/manager/dashboard',
            spv: '/spv/dashboard',
            technician: '/technician/dashboard'
        };
        const userDashboard = dashboardRoutes[req.session.userRole];
        if (userDashboard) {
            return res.redirect(userDashboard);
        } else {
            return res.redirect('/login');
        }
    }
    res.redirect('/login');
});


// ----- AUTHENTICATION ROUTES -----
app.get('/login', (req, res) => {
    res.render('login');
});

app.post('/login', async (req, res) => {
    try {
        const { email, password } = req.body;
        const user = await User.findOne({ email });
        if (!user) return res.send('User not found');
        const match = await bcrypt.compare(password, user.password);
        if (!match) return res.send('Incorrect password');
        req.session.userId = user._id;
        req.session.userRole = user.role;
        req.session.userDivision = (user.role === 'spv' || user.role === 'technician') && user.division ? user.division.toString() : null;

        await logActivity(user._id, `logged in to the system.`);

        res.redirect('/');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/logout', (req, res) => {
    req.session.destroy();
    res.redirect('/login');
});

// ----- SUPERUSER ROUTES -----
app.get('/superuser/dashboard', ensureAuthenticated, ensureSuperuser, (req, res) => {
    res.render('superuserDashboard');
});

// --- USER MANAGEMENT (SUPERUSER) ---
app.get('/admin/users', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const users = await User.find({}).populate('division');
        res.render('ManageUsers', { users });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/admin/users/new', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    const divisions = await Division.find({});
    res.render('newUser', { divisions });
});

app.post('/admin/users', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        let { name, email, password, role, division } = req.body;
        const hashedPassword = await bcrypt.hash(password, 10);
        if (role === 'superuser' || role === 'manager') {
            division = null;
        }
        const newUser = new User({ name, email, password: hashedPassword, role, division: division || null });
        await newUser.save();

        await logActivity(req.session.userId, `created a new user: ${name} (${role}).`);
        req.session.message = { type: 'success', text: 'User created successfully.' };
        res.redirect('/admin/users');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/admin/users/:id/edit', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const userToEdit = await User.findById(req.params.id);
        const divisions = await Division.find({});
        res.render('editUser', { userToEdit, divisions });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/admin/users/:id/edit', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        let { name, email, role, division, password } = req.body;
        const userToUpdate = await User.findById(req.params.id);

        userToUpdate.name = name;
        userToUpdate.email = email;
        userToUpdate.role = role;
        userToUpdate.division = (role === 'spv' || user.role === 'technician') ? division : null;

        if (password) {
            userToUpdate.password = await bcrypt.hash(password, 10);
        }

        await userToUpdate.save();
        await logActivity(req.session.userId, `updated user details for ${name}.`);
        req.session.message = { type: 'success', text: 'User updated successfully.' };
        res.redirect('/admin/users');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/admin/users/:id/delete', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const user = await User.findById(req.params.id);
        // Prevent superuser from deleting themselves
        if (user._id.toString() === req.session.userId) {
            req.session.message = { type: 'error', text: "You cannot delete your own account." };
            return res.redirect('/admin/users');
        }
        await User.findByIdAndDelete(req.params.id);
        await logActivity(req.session.userId, `deleted user: ${user.name}.`);
        req.session.message = { type: 'success', text: 'User deleted successfully.' };
        res.redirect('/admin/users');
    } catch (err) {
        res.status(500).send(err.message);
    }
});


// --- MASTER DATA MANAGEMENT (SUPERUSER) ---
app.get('/admin/manage-data', ensureAuthenticated, ensureSuperuser, (req, res) => {
    res.render('superuserManageData');
});

// Divisions
app.get('/admin/divisions', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    const divisions = await Division.find({});
    res.render('manageDivisions', { divisions });
});

app.post('/admin/divisions', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const { name } = req.body;
        const newDivision = new Division({ name });
        await newDivision.save();
        await logActivity(req.session.userId, `created a new division: ${name}.`);
        req.session.message = { type: 'success', text: 'Division created.' };
        res.redirect('/admin/divisions');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/admin/divisions/:id/delete', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const division = await Division.findById(req.params.id);
        // Add logic here to re-assign or handle users/assets in this division before deleting
        await Division.findByIdAndDelete(req.params.id);
        await logActivity(req.session.userId, `deleted division: ${division.name}.`);
        req.session.message = { type: 'success', text: 'Division deleted.' };
        res.redirect('/admin/divisions');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

// Asset Categories
app.get('/admin/asset-categories', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    const categories = await AssetCategory.find({});
    res.render('manageAssetCategories', { categories });
});

app.post('/admin/asset-categories', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const { name } = req.body;
        await AssetCategory.create({ name });
        await logActivity(req.session.userId, `created asset category: ${name}.`);
        req.session.message = { type: 'success', text: 'Category created.' };
        res.redirect('/admin/asset-categories');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/admin/asset-categories/:id/delete', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const category = await AssetCategory.findById(req.params.id);
        await AssetCategory.findByIdAndDelete(req.params.id);
        await logActivity(req.session.userId, `deleted asset category: ${category.name}.`);
        req.session.message = { type: 'success', text: 'Category deleted.' };
        res.redirect('/admin/asset-categories');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

// Floors and Zones
app.get('/admin/floors-zones', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    const floors = await Floor.find({}).populate('zones');
    const allZones = await Zone.find({});
    res.render('manageFloorsZones', { floors, allZones });
});

app.post('/admin/floors', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const { name } = req.body;
        await Floor.create({ name });
        await logActivity(req.session.userId, `created floor: ${name}.`);
        req.session.message = { type: 'success', text: 'Floor created.' };
        res.redirect('/admin/floors-zones');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/admin/zones', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const { name, floorId } = req.body;
        await Zone.create({ name, floor: floorId });
        const floor = await Floor.findById(floorId);
        await logActivity(req.session.userId, `created zone "${name}" on floor "${floor.name}".`);
        req.session.message = { type: 'success', text: 'Zone created.' };
        res.redirect('/admin/floors-zones');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/admin/floors/:id/delete', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const floor = await Floor.findById(req.params.id);
        await Zone.deleteMany({ floor: req.params.id });
        await Floor.findByIdAndDelete(req.params.id);
        await logActivity(req.session.userId, `deleted floor: ${floor.name} and all its zones.`);
        req.session.message = { type: 'success', text: 'Floor and zones deleted.' };
        res.redirect('/admin/floors-zones');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/admin/zones/:id/delete', ensureAuthenticated, ensureSuperuser, async (req, res) => {
    try {
        const zone = await Zone.findById(req.params.id).populate('floor');
        await Zone.findByIdAndDelete(req.params.id);
        await logActivity(req.session.userId, `deleted zone: ${zone.name} from floor ${zone.floor.name}.`);
        req.session.message = { type: 'success', text: 'Zone deleted.' };
        res.redirect('/admin/floors-zones');
    } catch (err) {
        res.status(500).send(err.message);
    }
});


// ---------- MANAGER ROUTES ----------//
app.get('/manager/dashboard', ensureAuthenticated, ensureManager, async (req, res) => {
    try {
        const { filter = 'all', division = 'all', floor = 'all', submittedBy = 'all' } = req.query;

        const matchCondition = { completedAt: { $ne: null } };

        if (filter !== 'all') {
            if (filter === 'rejected') {
                matchCondition.verifiedStatus = 'rejected';
            } else {
                matchCondition.verifiedStatus = { $ne: 'rejected' };
                if (filter === 'verified_spv') {
                    matchCondition.verifiedBySpv = true;
                    matchCondition.verifiedByManager = false;
                } else if (filter === 'verified_manager') {
                    matchCondition.verifiedByManager = true;
                } else if (filter === 'has_alert') {
                    matchCondition.hasAlert = true;
                }
            }
        }

        if (division !== 'all') {
            matchCondition.division = division;
        }

        if (submittedBy !== 'all') {
            matchCondition.submittedBy = submittedBy;
        }

        let assignments = await ChecklistAssignment.find(matchCondition)
            .populate({
                path: 'asset',
                populate: { path: 'floor' }
            })
            .populate('submittedBy')
            .populate('verifiedBySpvUser')
            .populate('verifiedByManagerUser')
            .populate('rejectedBy');

        if (floor !== 'all') {
            assignments = assignments.filter(a => a.asset && a.asset.floor && a.asset.floor._id.toString() === floor);
        }

        const divisions = await Division.find({});
        const floors = await Floor.find({});
        const technicians = await User.find({ role: 'technician' });
        const activities = await Activity.find({}).sort({ timestamp: -1 }).limit(20);

        res.render('managerDashboard', {
            assignments,
            currentFilter: filter,
            divisions,
            currentDivision: division,
            floors,
            currentFloor: floor,
            technicians,
            currentSubmittedBy: submittedBy,
            activities
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/manager/report/:assignmentId/verify', ensureAuthenticated, ensureManager, async (req, res) => {
    try {
        const user = await User.findById(req.session.userId);
        if (!user) {
            return res.status(401).json({ success: false, message: 'User not found.' });
        }
        const assignment = await ChecklistAssignment.findByIdAndUpdate(
            req.params.assignmentId, {
                verifiedByManager: true,
                verifiedByManagerUser: req.session.userId,
                verifiedByManagerUserName: user.name,
                verifiedStatus: 'pending'
            }
        ).populate('asset');

        await logActivity(req.session.userId, `verified a report for asset: ${assignment.asset.name}.`, assignment.division);

        if (req.body.fromDetail) {
            req.session.message = { type: 'success', text: 'Report verified successfully.' };
            return res.redirect(`/manager/report/${req.params.assignmentId}/detail`);
        } else {
            return res.json({ success: true, status: 'verified' });
        }
    } catch (err) {
        console.error('Error verifying by manager:', err);
        if (req.body.fromDetail) {
            req.session.message = { type: 'danger', text: 'Failed to verify report.' };
            return res.redirect(`/manager/report/${req.params.assignmentId}/detail`);
        } else {
            return res.status(500).json({ success: false, message: err.message });
        }
    }
});

app.post('/manager/report/:assignmentId/reject', ensureAuthenticated, ensureManager, async (req, res) => {
    try {
        const user = await User.findById(req.session.userId);
        if (!user) {
            return res.status(401).json({ success: false, message: 'User not found.' });
        }
        const assignment = await ChecklistAssignment.findByIdAndUpdate(
            req.params.assignmentId, {
                verifiedStatus: 'rejected',
                rejectedBy: req.session.userId,
                rejectedByName: user.name,
                verifiedByManager: false
            }
        ).populate('asset');

        await logActivity(req.session.userId, `rejected a report for asset: ${assignment.asset.name}.`, assignment.division);

        if (req.body.fromDetail) {
            req.session.message = { type: 'success', text: 'Report rejected successfully.' };
            return res.redirect(`/manager/report/${req.params.assignmentId}/detail`);
        } else {
            return res.json({ success: true, status: 'rejected' });
        }
    } catch (err) {
        console.error('Error rejecting by manager:', err);
        if (req.body.fromDetail) {
            req.session.message = { type: 'danger', text: 'Failed to reject report.' };
            return res.redirect(`/manager/report/${req.params.assignmentId}/detail`);
        } else {
            return res.status(500).json({ success: false, message: err.message });
        }
    }
});

app.get('/manager/report/:assignmentId/detail', ensureAuthenticated, ensureManager, async (req, res) => {
    try {
        const assignment = await ChecklistAssignment.findById(req.params.assignmentId)
            .populate({
                path: 'asset',
                populate: ['floor', 'category', 'zone', 'division']
            })
            .populate('submittedBy')
            .populate('verifiedBySpvUser')
            .populate('verifiedByManagerUser')
            .populate('rejectedBy');

        if (!assignment || !assignment.completedAt) {
            return res.status(404).send('Checklist not found or not completed');
        }

        res.render('managerChecklistReportDetail', {
            assignment
        });
    } catch (err) {
        console.error(err);
        res.status(500).send(err.message);
    }
});

// ---------- SPV ROUTES ----------//
app.get('/spv/report', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const { filter = 'all', floor = 'all', submittedBy = 'all' } = req.query;

        const query = {
            division: req.session.userDivision,
            completedAt: { $ne: null }
        };

        if (filter !== 'all') {
            if (filter === 'rejected') {
                 query.verifiedStatus = 'rejected';
            } else {
                query.verifiedStatus = { $ne: 'rejected' };
                if (filter === 'verified_spv') {
                    query.verifiedBySpv = true;
                    query.verifiedByManager = false;
                } else if (filter === 'verified_manager') {
                    query.verifiedByManager = true;
                } else if (filter === 'has_alert') {
                    query.hasAlert = true;
                }
            }
        }

        if (submittedBy !== 'all') {
            query.submittedBy = submittedBy;
        }

        let assignments = await ChecklistAssignment.find(query)
            .populate({
                path: 'asset',
                populate: { path: 'floor' }
            })
            .populate('submittedBy')
            .populate('rejectedBy');

        if (floor !== 'all') {
            assignments = assignments.filter(a => a.asset && a.asset.floor && a.asset.floor._id.toString() === floor);
        }

        const floors = await Floor.find({});
        const technicians = await User.find({ role: 'technician', division: req.session.userDivision });

        res.render('spvReport', {
            assignments,
            currentFilter: filter,
            floors,
            currentFloor: floor,
            technicians,
            currentSubmittedBy: submittedBy
        });
    } catch (err) {
        console.error("Error fetching SPV report:", err);
        res.status(500).send(err.message);
    }
});

app.post('/spv/report/:assignmentId/verify', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const user = await User.findById(req.session.userId);
        if (!user) {
            return res.status(401).json({ success: false, message: 'User not found.' });
        }
        const assignment = await ChecklistAssignment.findByIdAndUpdate(
            req.params.assignmentId, {
                verifiedBySpv: true,
                verifiedBySpvUser: req.session.userId,
                verifiedBySpvUserName: user.name,
                verifiedStatus: 'pending'
            }
        ).populate('asset');

        await logActivity(req.session.userId, `verified a report for asset: ${assignment.asset.name}.`);

        if (req.body.fromDetail) {
            req.session.message = { type: 'success', text: 'Report verified successfully.' };
            return res.redirect(`/spv/report/${req.params.assignmentId}/detail`);
        } else {
            return res.json({ success: true, status: 'verified' });
        }
    } catch (err) {
        if (req.body.fromDetail) {
            req.session.message = { type: 'danger', text: 'Failed to verify report.' };
            return res.redirect(`/spv/report/${req.params.assignmentId}/detail`);
        } else {
            return res.status(500).json({ success: false, message: err.message });
        }
    }
});

app.post('/spv/report/:assignmentId/reject', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const user = await User.findById(req.session.userId);
        if (!user) {
            return res.status(401).json({ success: false, message: 'User not found.' });
        }
        const assignment = await ChecklistAssignment.findByIdAndUpdate(req.params.assignmentId, {
            verifiedStatus: 'rejected',
            rejectedBy: req.session.userId,
            rejectedByName: user.name,
            verifiedBySpv: false
        }).populate('asset');

        await logActivity(req.session.userId, `rejected a report for asset: ${assignment.asset.name}.`);

        if (req.body.fromDetail) {
            req.session.message = { type: 'success', text: 'Report rejected successfully.' };
            return res.redirect(`/spv/report/${req.params.assignmentId}/detail`);
        } else {
            return res.json({ success: true, status: 'rejected' });
        }
    } catch (err) {
        if (req.body.fromDetail) {
            req.session.message = { type: 'danger', text: 'Failed to reject report.' };
            return res.redirect(`/spv/report/${req.params.assignmentId}/detail`);
        } else {
            return res.status(500).json({ success: false, message: err.message });
        }
    }
});

app.get('/spv/report/:assignmentId/detail', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const assignment = await ChecklistAssignment.findById(req.params.assignmentId)
            .populate({
                path: 'asset',
                populate: ['floor', 'category', 'zone']
            })
            .populate('submittedBy')
            .populate('verifiedBySpvUser')
            .populate('verifiedByManagerUser')
            .populate('rejectedBy');

        if (!assignment || !assignment.completedAt) {
            return res.status(404).send('Checklist not completed or not found.');
        }

        res.render('spvChecklistReportDetail', {
            assignment
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/spv/dashboard', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        // Ambil checklist berdasarkan divisi SPV
        const checklists = await Checklist.find({ division: req.session.userDivision }).sort({ order: 1 });
        const checklistData = await Promise.all(checklists.map(async checklist => {
            const count = await ChecklistAssignment.countDocuments({ checklist: checklist._id, isTemplate: true });
            return { ...checklist.toObject(), assignmentCount: count };
        }));

        const assets = await Asset.find({ division: req.session.userDivision })
            .sort({ order: 1 }) // Sort assets by order
            .populate('category')
            .populate('floor')
            .populate('zone');

        const assetCategories = await AssetCategory.find({});
        const floors = await Floor.find({});

        // Ambil aktivitas untuk SPV
        const activities = await Activity.find({
            $or: [
                { 'division.id': req.session.userDivision },
                { role: 'manager' }
            ]
        }).sort({ timestamp: -1 }).limit(20);

        res.render('spvDashboard', {
            checklists: checklistData,
            assets,
            assetCategories,
            floors,
            user: req.session,
            message: res.locals.message,
            activities
        });

    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/assets/new', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const assetCategories = await AssetCategory.find({});
        const floors = await Floor.find({});
        const zones = await Zone.find({});
        res.render('createAsset', {
            assetCategories,
            floors,
            zones,
            user: req.session
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/assets', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const { name, description, location, category, floor, zone } = req.body;
        const division = req.session.userDivision;

        const existingAsset = await Asset.findOne({ name: name, division: division });
        if (existingAsset) {
            req.session.message = { type: 'error', text: `Asset with name "${name}" already exists in this division.` };
            return res.redirect('/spv/dashboard');
        }

        const newAsset = new Asset({ name, description, location, category, floor, zone, division });
        await newAsset.save();

        const qrCodeDataUrl = await qrcode.toDataURL(newAsset._id.toString());
        newAsset.qrCode = qrCodeDataUrl;
        await newAsset.save();

        await logActivity(req.session.userId, `created a new asset: ${name}.`);

        req.session.message = { type: 'success', text: 'Asset created successfully.' };
        res.redirect('/spv/dashboard');
    } catch (err) {
        req.session.message = { type: 'error', text: 'Error creating asset.' };
        res.redirect('/spv/dashboard');
    }
});

app.get('/assets/:id/edit', ensureAuthenticated, ensureSpv, ensureAssetBelongsToUser, async (req, res) => {
    try {
        const assetCategories = await AssetCategory.find({});
        const floors = await Floor.find({});
        const zones = await Zone.find({});
        res.render('editAsset', {
            asset: req.asset,
            assetCategories,
            floors,
            zones
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/assets/:id/edit', ensureAuthenticated, ensureSpv, ensureAssetBelongsToUser, async (req, res) => {
    try {
        const { name, description, location, category, floor, zone } = req.body;

        const existingAsset = await Asset.findOne({ name: name, division: req.session.userDivision, _id: { $ne: req.params.id } });
        if (existingAsset) {
            req.session.message = { type: 'error', text: `Another asset with name "${name}" already exists.` };
            return res.redirect('/spv/dashboard');
        }

        req.asset.name = name;
        req.asset.description = description;
        req.asset.location = location;
        req.asset.category = category;
        req.asset.floor = floor;
        req.asset.zone = zone;
        await req.asset.save();

        await logActivity(req.session.userId, `edited asset: ${name}.`);

        req.session.message = { type: 'success', text: 'Asset updated successfully.' };
        res.redirect('/spv/dashboard');
    } catch (err) {
        req.session.message = { type: 'error', text: 'Error updating asset.' };
        res.redirect('/spv/dashboard');
    }
});

app.post('/assets/:id/duplicate', ensureAuthenticated, ensureSpv, ensureAssetBelongsToUser, async (req, res) => {
    try {
        const originalAsset = req.asset;

        const copyRegex = /^(.*) \(Copy (\d+)\)$/;
        const baseNameMatch = originalAsset.name.match(copyRegex);
        const baseName = baseNameMatch ? baseNameMatch[1].trim() : originalAsset.name.trim();

        const searchRegex = new RegExp(`^${escapeRegex(baseName)} \\(Copy (\\d+)\\)$`);
        const relatedAssets = await Asset.find({
            division: req.session.userDivision,
            name: { $regex: `^${escapeRegex(baseName)}` }
        });

        let maxCopyNum = 0;
        relatedAssets.forEach(asset => {
            const assetMatch = asset.name.match(searchRegex);
            if (assetMatch) {
                const copyNum = parseInt(assetMatch[1], 10);
                if (copyNum > maxCopyNum) {
                    maxCopyNum = copyNum;
                }
            }
        });

        const newName = `${baseName} (Copy ${maxCopyNum + 1})`;

        const newAsset = new Asset({
            name: newName,
            description: originalAsset.description,
            location: originalAsset.location,
            category: originalAsset.category,
            floor: originalAsset.floor,
            zone: originalAsset.zone,
            division: originalAsset.division
        });

        await newAsset.save();

        await logActivity(req.session.userId, `duplicated asset: ${originalAsset.name} to ${newName}.`);

        req.session.message = { type: 'success', text: `Asset "${originalAsset.name}" duplicated successfully as "${newName}".` };
        res.redirect('/spv/dashboard');
    } catch (err) {
        console.error("Error duplicating asset:", err);
        req.session.message = { type: 'error', text: 'Failed to duplicate asset.' };
        res.redirect('/spv/dashboard');
    }
});

app.get('/assets/:id/delete', ensureAuthenticated, ensureSpv, ensureAssetBelongsToUser, async (req, res) => {
    try {
        const assetName = req.asset.name;
        await Asset.findByIdAndDelete(req.params.id);

        await logActivity(req.session.userId, `deleted asset: ${assetName}.`);

        req.session.message = { type: 'success', text: 'Asset deleted successfully.' };
        res.redirect('/spv/dashboard');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/checklists/new', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const existingChecklists = await Checklist.find({});
        res.render('createChecklist', {
            existingChecklists
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/checklists', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const {
            title,
            taskDescriptions,
            taskInputTypes,
            taskExpectedUnits,
            taskMinRanges,
            taskMaxRanges
        } = req.body;

        let tasks = [];
        const descArr = Array.isArray(taskDescriptions) ? taskDescriptions : [taskDescriptions];
        const typeArr = Array.isArray(taskInputTypes) ? taskInputTypes : [taskInputTypes];
        const unitArr = Array.isArray(taskExpectedUnits) ? taskExpectedUnits : [taskExpectedUnits];
        const minArr = Array.isArray(taskMinRanges) ? taskMinRanges : [taskMinRanges];
        const maxArr = Array.isArray(taskMaxRanges) ? taskMaxRanges : [taskMaxRanges];

        for (let i = 0; i < descArr.length; i++) {
            tasks.push({
                description: descArr[i],
                inputType: typeArr[i],
                expectedUnit: unitArr[i] || '',
                minRange: minArr[i] ? Number(minArr[i]) : null,
                maxRange: maxArr[i] ? Number(maxArr[i]) : null,
            });
        }

        const newChecklist = new Checklist({
            title,
            tasks,
            createdBy: req.session.userId,
            division: req.session.userDivision // Tambahkan divisi saat membuat
        });
        await newChecklist.save();

        await logActivity(req.session.userId, `created a new checklist: ${title}.`);

        res.redirect('/spv/dashboard');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/api/checklists/:id/tasks', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const checklist = await Checklist.findById(req.params.id);
        if (!checklist) {
            return res.status(404).json({
                error: 'Checklist not found'
            });
        }
        res.json(checklist.tasks);
    } catch (err) {
        res.status(500).json({
            error: err.message
        });
    }
});

app.get('/checklists/:id/edit', ensureAuthenticated, ensureSpv, ensureChecklistBelongsToDivision, async (req, res) => {
    try {
        res.render('editChecklist', {
            checklist: req.checklist // checklist didapat dari middleware
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/checklists/:id/edit', ensureAuthenticated, ensureSpv, ensureChecklistBelongsToDivision, async (req, res) => {
    try {
        const {
            title,
            taskDescriptions,
            taskInputTypes,
            taskExpectedUnits,
            taskMinRanges,
            taskMaxRanges
        } = req.body;

        const checklist = req.checklist; // Ambil checklist dari middleware

        checklist.title = title;
        const tasks = [];
        const descArr = Array.isArray(taskDescriptions) ? taskDescriptions : [taskDescriptions];
        const typeArr = Array.isArray(taskInputTypes) ? taskInputTypes : [taskInputTypes];
        const unitArr = Array.isArray(taskExpectedUnits) ? taskExpectedUnits : [taskExpectedUnits];
        const minArr = Array.isArray(taskMinRanges) ? taskMinRanges : [taskMinRanges];
        const maxArr = Array.isArray(taskMaxRanges) ? taskMaxRanges : [taskMaxRanges];

        if (descArr) {
            for (let i = 0; i < descArr.length; i++) {
                tasks.push({
                    description: descArr[i],
                    inputType: typeArr[i],
                    expectedUnit: unitArr[i] || '',
                    minRange: (minArr[i] !== null && minArr[i] !== '') ? Number(minArr[i]) : null,
                    maxRange: (maxArr[i] !== null && maxArr[i] !== '') ? Number(maxArr[i]) : null,
                });
            }
        }

        checklist.tasks = tasks;
        await checklist.save();

        await logActivity(req.session.userId, `edited checklist: ${title}.`);

        res.redirect('/spv/dashboard');
    } catch (err) {
        console.error('Error editing checklist:', err);
        res.status(500).send(err.message);
    }
});

app.get('/checklists/:id/assign', ensureAuthenticated, ensureSpv, ensureChecklistBelongsToDivision, async (req, res) => {
    try {
        const assignments = await ChecklistAssignment.find({
            checklist: req.params.id,
            isTemplate: true
        });
        const assignedAssetIds = assignments.map(a => a.asset.toString());

        const assets = await Asset.find({
            division: req.session.userDivision
        });

        res.render('assignChecklist', {
            checklist: req.checklist,
            assets,
            assignedAssetIds
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/checklists/:id/assign', ensureAuthenticated, ensureSpv, ensureChecklistBelongsToDivision, async (req, res) => {
    try {
        const checklistId = req.params.id;
        const { assetIds } = req.body;
        const checklist = req.checklist; // Ambil dari middleware

        await ChecklistAssignment.deleteMany({
            checklist: checklistId,
            isTemplate: true
        });

        const assetsToAssign = Array.isArray(assetIds) ? assetIds : assetIds ? [assetIds] : [];

        const assets = await Asset.find({ '_id': { $in: assetsToAssign } }).populate('division');
        const assetMap = new Map(assets.map(asset => [asset._id.toString(), asset]));

        const newAssignments = assetsToAssign.map(assetId => {
            const asset = assetMap.get(assetId);
            return {
                checklist: checklistId,
                asset: assetId,
                isTemplate: true,
                checklistTitle: checklist.title,
                assetSnapshot: { name: asset.name },
                division: asset.division._id
            };
        });

        if (newAssignments.length > 0) {
            await ChecklistAssignment.insertMany(newAssignments);
        }

        await logActivity(req.session.userId, `assigned checklist "${checklist.title}" to ${assetsToAssign.length} assets.`);

        res.redirect('/spv/dashboard');
    } catch (err) {
        console.error('Error in POST /checklists/:id/assign:', err);
        res.status(500).send(err.message);
    }
});

app.get('/checklists/:id/delete', ensureAuthenticated, ensureSpv, ensureChecklistBelongsToDivision, async (req, res) => {
    try {
        const checklistTitle = req.checklist.title;
        await Checklist.deleteOne({
            _id: req.params.id
        });

        await logActivity(req.session.userId, `deleted checklist: ${checklistTitle}.`);

        res.redirect('/spv/dashboard');
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/checklists/sort', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const {
            order
        } = req.body;
        for (let i = 0; i < order.length; i++) {
            await Checklist.findByIdAndUpdate(order[i], {
                order: i
            });
        }
        res.status(200).json({
            message: 'Checklist order updated successfully.'
        });
    } catch (err) {
        res.status(500).json({
            error: err.message
        });
    }
});

app.post('/assets/sort', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const { order } = req.body; // Expects an array of asset IDs
        for (let i = 0; i < order.length; i++) {
            await Asset.findByIdAndUpdate(order[i], { order: i });
        }
        res.status(200).json({ message: 'Asset order updated successfully.' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// ---------- TECHNICIAN ROUTES ----------//
app.get('/technician/dashboard', ensureAuthenticated, ensureTechnician, async (req, res) => {
    try {
        const assets = await Asset.find({
                division: req.session.userDivision
            })
            .populate('floor')
            .populate('category')
            .populate('zone');
        const assetIds = assets.map(a => a._id);

        const assignments = await ChecklistAssignment.find({
                asset: {
                    $in: assetIds
                },
                isTemplate: true
            })
            .populate('checklist')
            .populate({
                path: 'asset',
                populate: ['floor', 'category', 'zone']
            });

        const floors = await Floor.find({});
        const assetCategories = await AssetCategory.find({});

        // Ambil aktivitas untuk Teknisi
        const activities = await Activity.find({
            $or: [
                { 'division.id': req.session.userDivision },
                { role: 'manager' }
            ]
        }).sort({ timestamp: -1 }).limit(20);

        res.render('technicianDashboard', {
            assignments,
            floors,
            assetCategories,
            activities
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/technician/checklist/:assignmentId', ensureAuthenticated, ensureTechnician, async (req, res) => {
    try {
        const assignment = await ChecklistAssignment.findById(req.params.assignmentId)
            .populate('checklist')
            .populate({
                path: 'asset',
                populate: ['floor', 'category', 'zone']
            });
        if (!assignment) {
            return res.status(404).send('Checklist assignment not found.');
        }
        res.render('technicianChecklist', {
            assignment
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.post('/technician/checklist/:assignmentId/submit', ensureAuthenticated, ensureTechnician, upload.any(), async (req, res) => {
    try {
        const assignmentId = req.params.assignmentId;

        const templateAssignment = await ChecklistAssignment.findById(assignmentId)
            .populate('checklist')
            .populate({
                path: 'asset',
                populate: ['floor', 'category', 'zone', 'division']
            });

        if (!templateAssignment || !templateAssignment.asset) {
            return res.status(404).send('Checklist assignment or associated asset not found.');
        }

        const user = await User.findById(req.session.userId);
        if (!user) {
            return res.status(401).send('Submitting user not found.');
        }

        let hasAlert = false;

        const tasksSnapshot = templateAssignment.checklist.tasks.map(t => ({
            originalTaskId: t._id,
            description: t.description,
            inputType: t.inputType,
            expectedUnit: t.expectedUnit || '',
            minRange: t.minRange,
            maxRange: t.maxRange,
        }));

        const responses = { ...(req.body.results || {})
        };

        for (const task of tasksSnapshot) {
            if (task.inputType === 'functional' && responses[task.originalTaskId.toString()] === 'fail') {
                hasAlert = true;
                break;
            } else if (task.inputType === 'measurement') {
                const value = parseFloat(responses[task.originalTaskId.toString()]);
                if (!isNaN(value) && task.minRange != null && task.maxRange != null) {
                    if (value < task.minRange || value > task.maxRange) {
                        hasAlert = true;
                        break;
                    }
                }
            }
        }

        const assetSnapshot = {
            name: templateAssignment.asset.name,
            description: templateAssignment.asset.description,
            location: templateAssignment.asset.location,
            category: templateAssignment.asset.category ? templateAssignment.asset.category.name : 'N/A',
            floor: templateAssignment.asset.floor ? templateAssignment.asset.floor.name : 'N/A',
            zone: templateAssignment.asset.zone ? templateAssignment.asset.zone.name : 'N/A',
            division: templateAssignment.asset.division ? templateAssignment.asset.division.name : 'N/A'
        };


        if (req.files && req.files.length > 0) {
            const filesByTask = {};
            req.files.forEach(file => {
                const match = file.fieldname.match(/^results\[(.+)\]$/);
                if (!match) return;
                const taskId = match[1];
                filesByTask[taskId] = filesByTask[taskId] || [];
                filesByTask[taskId].push(file.path);
            });

            const processingPromises = Object.entries(filesByTask).map(
                async ([taskId, filePaths]) => {
                    const processedUrls = await Promise.all(
                        filePaths.map(
                            filePath =>
                            new Promise((resolve, reject) => {
                                imageProcessingQueue.push({
                                    filePath
                                }, err => {
                                    if (err) return reject(err);
                                    const filename = path.basename(filePath);
                                    resolve(`/processed/${filename}`);
                                });
                            })
                        )
                    );
                    responses[taskId] = processedUrls;
                }
            );
            await Promise.all(processingPromises);
        }

        const maintenanceNote = req.body.note || '';

        const completedAssignment = new ChecklistAssignment({
            checklist: templateAssignment.checklist._id,
            checklistTitle: templateAssignment.checklist.title,
            asset: templateAssignment.asset._id,
            assetSnapshot: assetSnapshot,
            division: templateAssignment.asset.division._id,
            assignedAt: templateAssignment.assignedAt,
            tasksSnapshot,
            responses,
            completedAt: new Date(),
            submittedBy: req.session.userId,
            submittedByName: user.name,
            isTemplate: false,
            note: maintenanceNote,
            hasAlert: hasAlert
        });
        await completedAssignment.save();

        await logActivity(req.session.userId, `submitted a report for asset: ${templateAssignment.asset.name}.`);

        if (hasAlert) {
            io.emit('alert', {
                message: `Alert: Checklist for asset ${templateAssignment.asset.name} requires attention!`,
                assignmentId: completedAssignment._id
            })
        }

        res.redirect('/technician/dashboard');
    } catch (err) {
        console.error('Error submitting checklist:', err);
        res.status(500).send(err.message);
    }
});

app.get('/technician/report', ensureAuthenticated, ensureTechnician, async (req, res) => {
    try {
        const { submittedBy = 'all' } = req.query;

        const query = {
            completedAt: { $ne: null }
        };

        // If the filter is 'all', the technician sees all their reports.
        // If they select their own name, it still shows all their reports.
        // If they somehow select another user, this will filter for that user's reports.
        if (submittedBy !== 'all') {
            query.submittedBy = submittedBy;
        } else {
            // By default, a technician should only see their own reports
            query.submittedBy = req.session.userId;
        }

        const assignments = await ChecklistAssignment.find(query)
            .populate('asset')
            .populate('submittedBy');

        // For the filter dropdown, we only need the current user
        const technicians = await User.find({ _id: req.session.userId });

        res.render('technicianReport', {
            assignments,
            technicians,
            currentSubmittedBy: submittedBy
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/technician/report/:assignmentId', ensureAuthenticated, ensureTechnician, async (req, res) => {
    try {
        const assignment = await ChecklistAssignment.findById(req.params.assignmentId)
            .populate({
                path: 'asset',
                populate: ['floor', 'category', 'zone']
            })
            .populate('submittedBy')
            .populate('verifiedBySpvUser')
            .populate('verifiedByManagerUser')
            .populate('rejectedBy');

        if (!assignment || !assignment.completedAt) {
            return res.status(404).send('Completed checklist not found.');
        }

        res.render('technicianChecklistReportDetail', {
            assignment
        });
    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/asset/:id/qr', ensureAuthenticated, ensureSpv, async (req, res) => {
    try {
        const asset = await Asset.findById(req.params.id);
        if (!asset) {
            return res.status(404).send('Asset not found');
        }

        const qrCodeDataUrl = await qrcode.toDataURL(asset._id.toString());
        res.send(`<img src="${qrCodeDataUrl}" alt="QR Code for ${asset.name}">`);

    } catch (err) {
        res.status(500).send(err.message);
    }
});

app.get('/technician/asset/:id', ensureAuthenticated, ensureTechnician, async (req, res) => {
    try {
        const asset = await Asset.findById(req.params.id)
            .populate('floor')
            .populate('category')
            .populate('zone');

        if (!asset) {
            return res.status(404).send('Asset not found');
        }

        const assignments = await ChecklistAssignment.find({ asset: asset._id, isTemplate: true })
            .populate('checklist');

        res.render('assetDetail', { asset, assignments });
    } catch (err) {
        res.status(500).send(err.message);
    }
});



// ------------------------------
// START SERVER
// ------------------------------
const PORT = process.env.PORT || 5000;
server.listen(PORT, '0.0.0.0', () => console.log(`Server running on port ${PORT}`));

module.exports = app;